services:
  mongo:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo_data:/data/db
    networks:
      - listly_network

  meilisearch:
    image: getmeili/meilisearch:v1.12
    restart: always
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_ENV: production
      MEILI_DB_PATH: /meili_data
    volumes:
      - meili_data:/meili_data
    networks:
      - listly_network

  app:
    build: .
    restart: on-failure
    environment:
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/${MONGO_DATABASE}?authSource=admin
      MEILI_HOST: http://meilisearch:7700
      MEILI_API_KEY: ${MEILI_MASTER_KEY}
      MEILI_INDEX: media_items
    depends_on:
      - mongo
      - meilisearch
    ports:
      - "8080:8080"
    networks:
      - listly_network

volumes:
  mongo_data:
  meili_data:

networks:
  listly_network:
    driver: bridge
