services:
  mongo:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: listly_admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
      MONGO_INITDB_DATABASE: listlydb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  meilisearch:
    image: getmeili/meilisearch:v1.12
    restart: always
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_ENV=development
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data

  app:
    build: .
    restart: on-failure
    environment:
      - MONGO_URI=mongodb://listly_admin:secret123@mongo:27017/listlydb?authSource=admin
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_API_KEY=masterKey
      - MEILI_INDEX=media_items
    depends_on:
      - mongo
      - meilisearch
    ports:
      - "8080:8080"

volumes:
  mongo_data:
  meili_data:
